from typing import Protocol
from app.domain.entities.organisation import Organisation

class OrganisationRepository(Protocol):
    def create(self, org: Organisation) -> Organisation: ...
    def get_by_id(self, organisation_id: int) -> Organisation | None: ...
    def list(self, limit: int, offset: int) -> list[Organisation]: ...
    def update(self, org: Organisation) -> Organisation: ...
    def delete(self, organisation_id: int) -> bool: ...
